# Generated by Django 2.2.3 on 2019-07-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('condition', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('operator', models.CharField(choices=[('<', 'Less than'), ('>', 'Greater than'), ('<>', 'Not equals'), ('equals', 'Equal')], max_length=20)),
                ('value', models.CharField(max_length=60)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.WorkFlow')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('origin_node', models.CharField(max_length=40)),
                ('destination_node', models.CharField(max_length=40)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.WorkFlow')),
            ],
        ),
    ]
